### ISSUE TITLE
Implementing an ML algo to predict chance of the user to get into a particular college based on previous data

### ISSUE THREAD

**Issue by justanotherlad** [swastikbanerjee07/CollegeGyan_bot#7]
If the user has already given an examination for a university, then the bot will be able to predict his/her chances of getting into the particular university based on the score using an ML algorithm.

**Comment by rob-deans** [comment]
Have you got the data for this? Would quite like to help out on it

**Comment by justanotherlad** [comment]
@rob-deans No, but we can scrape it.

I made the basic bot initially by manually collecting datas from the net.

**Comment by justanotherlad** [comment]
@rob-deans are you taking up the issue?

**Comment by rob-deans** [comment]
If you point me it the right direction for the data I can do
